Adding connectedApp authentication to HTTP Wrapper
avioconsulting/mule-deploy-library pull request #39
Opened 2022-03-17 17:30 UTC by TimGonz-AVIO

Added connectedAppId/Secret as params to HTTP Wrapper and bubbled up through constructor calls and tests. Added additional function to handle connected app auth.

Added anypoint.connected-app.id and anypoint.connected-app.secret as plugin properties
Added --anypoint-connected-app-id (-i) and --anypoint-connected-app-secret (-s) as CLI params

2022-11-01 13:02 UTC, manikmagar commented on cli/src/main/java/com/avioconsulting/mule/cli/DeployerCommandLine.groovy
> +    private String anypointConnectedAppSecret
Instead of `-i` `-s` which sounds very generic, should we use something `-caid` `-casec`?

2022-11-01 13:06 UTC, manikmagar commented on library/src/main/java/com/avioconsulting/mule/deployment/internal/http/HttpClientWrapper.groovy
> +                      String connectedAppSecret = null,
Should we introduce Something like `Credential` model to allow instances like `UsernamePasswordCredential`, `ConnectedAppCredential`? All methods requiring credentials can be use this as argument, instead of passing multiple arguments.

2022-11-01 13:07 UTC, manikmagar commented on library/src/main/java/com/avioconsulting/mule/deployment/internal/http/HttpClientWrapper.groovy
> +                      String connectedAppSecret = null,
Should we introduce Something like `Credential` model to allow instances like `UsernamePasswordCredential`, `ConnectedAppCredential`? All methods requiring credentials can be use this as argument, instead of passing multiple arguments.

2022-11-04 13:16 UTC, manikmagar commented on library/src/main/java/com/avioconsulting/mule/deployment/internal/http/HttpClientWrapper.groovy
> +                      String connectedAppSecret = null,
Resolved in https://github.com/avioconsulting/mule-deploy-library/pull/39/commits/bca29c71a21476d9840ffd9bccc8a5ede1f5f1ca

2022-11-04 13:16 UTC, manikmagar commented on cli/src/main/java/com/avioconsulting/mule/cli/DeployerCommandLine.groovy
> +    private String anypointConnectedAppSecret
Resolved in https://github.com/avioconsulting/mule-deploy-library/pull/39/commits/bca29c71a21476d9840ffd9bccc8a5ede1f5f1ca

2022-11-07 16:43 UTC, adesjardin approved these changes

2022-11-07 16:45 UTC, adesjardin requested changes
Can we change the version to 1.2-SNAPSHOT in the pom.xml since this is merging into master?

2022-11-07 16:50 UTC, adesjardin approved these changes

2022-11-07 16:52 UTC, merged